[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'vim-scripts/AnsiEsc.vim'

[[plugins]]
repo = 'dracula/vim'
hook_add = '''
syntax enable
colorscheme dracula
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['/vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
set laststatus=2
let g:airline#extentions#tabline#enabled=1
let g:airline#extentions#tabline#buffer_idx_mode=1
let g:airline#extentions#whitespace#mixed_indent_algo=1
let g:airline_theme='dark'
'''
