[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html', 'vue']
hook_add = '''
let g:html5_event_handler_attributes_complete=1
let g:html5_rdfa_attributes_complete=1
let g:html5_microdata_attributes_complete=1
let g:html5_aria_attributes_complete=1
'''

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-rails'
on_fr = ['ruby']

[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_fr = ['ruby']

[[plugins]]
repo = 'alpaca-tc/vim-endwise.git'
on_ft = ['ruby']
hooK_add = '''
let g:endwise_no_mappings = 1
'''

[[plugins]]
repo = 'jelera/vim-javascript-syntax'
on_ft = ['javascript']

[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = ['pug']

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css', 'scss', 'sass']

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
on_ft = ['css', 'scss', 'sass']

[[plugin]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'elzr/vim-json'
hook_add = '''
let g:vim_json_syntax_conceal = 0
'''
on_ft = ['json']
